{
 "title": "Base de datos",
 "time": { "from": "1985-01-01T00:00:00.000Z", "to": "2002-08-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Empleados por género",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gender as \"Género\",\n  count(*) as \"Cantidad\"\nFROM employees e\nJOIN dept_emp de ON e.emp_no = de.emp_no\nWHERE de.to_date > current_date -- Solo activos\nGROUP BY gender;"
    }
   ]
  },
  {
   "title": "Distribución de cargos",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  title as \"Cargo\",\n  count(*) as \"Total\"\nFROM titles\nWHERE to_date > current_date -- Solo cargos actuales\nGROUP BY title\nORDER BY \"Total\" DESC;"
    }
   ]
  },
  {
   "title": "Empleados por Departamento",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  d.dept_name as \"Departamento\",\n  count(de.emp_no) as \"Empleados\"\nFROM departments d\nJOIN dept_emp de ON d.dept_no = de.dept_no\nWHERE de.to_date > current_date\nGROUP BY d.dept_name\nORDER BY \"Empleados\" DESC;"
    }
   ]
  },
  {
   "title": "Evolución de la brecha salarial",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  s.from_date as time, \n  e.gender as metric, \n  avg(s.salary) as value\nFROM salaries s\nJOIN employees e ON s.emp_no = e.emp_no\nGROUP BY s.from_date, e.gender\nORDER BY s.from_date ASC;"
    }
   ]
  },
  {
   "title": "Gasto salarial por departamento",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  d.dept_name as \"Departamento\",\n  sum(s.salary) as \"Presupuesto Nómina\"\nFROM departments d\nJOIN dept_emp de ON d.dept_no = de.dept_no\nJOIN salaries s ON de.emp_no = s.emp_no\nWHERE de.to_date > current_date\n  AND s.to_date > current_date\nGROUP BY d.dept_name\nORDER BY \"Presupuesto Nómina\" DESC;"
    }
   ]
  }
 ]
}